const { ObjectId } = require('./utils');

module.exports = [
  /* 1 */
  {
    _id: ObjectId('5d0d2ee62d386ba92eb7e34c'),
    color: '#f26247',
    messageType: 'JOINED_ROOM',
    isTrashed: false,
    user: ObjectId('5d0d2eae535e3a522445f7a4'),
    room: ObjectId('5d0d2ed0535e3a522445f7a7'),
    text: 'w_crush joined reference room',
    autogenerated: true,
    timestamp: 1561145062465.0,
    __v: 0,
  },

  /* 2 */
  {
    _id: ObjectId('5d0d2eea65fc7fd8b17ccd19'),
    color: '#f26247',
    messageType: 'TOOK_CONTROL',
    isTrashed: false,
    user: ObjectId('5d0d2eae535e3a522445f7a4'),
    room: ObjectId('5d0d2ed0535e3a522445f7a7'),
    text: 'w_crush took control',
    autogenerated: true,
    timestamp: 1561145066975.0,
    __v: 0,
  },

  /* 3 */
  {
    _id: ObjectId('5d0d2efc5faad4ca26214f33'),
    color: '#f26247',
    messageType: 'RELEASED_CONTROL',
    isTrashed: false,
    user: ObjectId('5d0d2eae535e3a522445f7a4'),
    room: ObjectId('5d0d2ed0535e3a522445f7a7'),
    text: 'w_crush released control',
    autogenerated: true,
    timestamp: 1561145084310.0,
    __v: 0,
  },

  /* 4 */
  {
    _id: ObjectId('5d0d2f0748e22b165488897c'),
    color: '#f26247',
    messageType: 'TEXT',
    isTrashed: false,
    text: 'segment g',
    user: ObjectId('5d0d2eae535e3a522445f7a4'),
    room: ObjectId('5d0d2ed0535e3a522445f7a7'),
    timestamp: 1561145095373.0,
    reference: {
      element: 'g',
      elementType: 'poly',
      tab: ObjectId('5d0d2ed0535e3a522445f7a9'),
    },
    __v: 0,
  },

  /* 5 */
  {
    _id: ObjectId('5d0d2f1634e454ff962b358f'),
    color: '#f26247',
    messageType: 'TEXT',
    isTrashed: false,
    text: 'poly q1',
    user: ObjectId('5d0d2eae535e3a522445f7a4'),
    room: ObjectId('5d0d2ed0535e3a522445f7a7'),
    timestamp: 1561145110586.0,
    reference: {
      element: 'q1',
      elementType: 'poly',
      tab: ObjectId('5d0d2ed0535e3a522445f7a9'),
    },
    __v: 0,
  },

  /* 6 */
  {
    _id: ObjectId('5d0d2f27e99a7ffce8aae28e'),
    color: '#f26247',
    messageType: 'TEXT',
    isTrashed: false,
    text: 'circle f',
    user: ObjectId('5d0d2eae535e3a522445f7a4'),
    room: ObjectId('5d0d2ed0535e3a522445f7a7'),
    timestamp: 1561145127034.0,
    reference: {
      element: 'f',
      elementType: 'circle',
      tab: ObjectId('5d0d2ed0535e3a522445f7a9'),
    },
    __v: 0,
  },

  /* 7 */
  {
    _id: ObjectId('5d0d2f2c535e3a522445f7c0'),
    color: '#333',
    messageType: 'LEFT_ROOM',
    isTrashed: false,
    room: ObjectId('5d0d2ed0535e3a522445f7a7'),
    user: ObjectId('5d0d2eae535e3a522445f7a4'),
    text: 'w_crush left the room',
    autogenerated: true,
    timestamp: 1561145132403.0,
    __v: 0,
  },

  /* 8 */
  {
    _id: ObjectId('5d8e1c20f61e66114f5a9aab'),
    messageType: 'JOINED_ROOM',
    color: '#f26247',
    isTrashed: false,
    user: ObjectId('5d1a59d79c78ad48c0480caa'),
    room: ObjectId('5d83f029dd0c4946d81684d2'),
    text: 'ssmith joined ssmith public desmos',
    autogenerated: true,
    timestamp: 1569594400341.0,
    __v: 0,
  },

  /* 9 */
  {
    _id: ObjectId('5d8e1c37fc4d0b4c1c8873ba'),
    messageType: 'TOOK_CONTROL',
    color: '#f26247',
    isTrashed: false,
    user: ObjectId('5d1a59d79c78ad48c0480caa'),
    room: ObjectId('5d83f029dd0c4946d81684d2'),
    text: 'ssmith took control',
    autogenerated: true,
    timestamp: 1569594423953.0,
    __v: 0,
  },

  /* 10 */
  {
    _id: ObjectId('5d8e1c9583074a44e85d97e0'),
    messageType: 'TEXT',
    color: '#f26247',
    isTrashed: false,
    text: 'can you see those functions?',
    user: ObjectId('5d1a59d79c78ad48c0480caa'),
    room: ObjectId('5d83f029dd0c4946d81684d2'),
    timestamp: 1569594517407.0,
    __v: 0,
  },

  /* 11 */
  {
    _id: ObjectId('5d8e1ca633014c946f1fcb6e'),
    messageType: 'LEFT_ROOM',
    color: '#333',
    isTrashed: false,
    room: ObjectId('5d83f029dd0c4946d81684d2'),
    user: ObjectId('5d1a59d79c78ad48c0480caa'),
    text: 'ssmith left the room',
    autogenerated: true,
    timestamp: 1569594534453.0,
    __v: 0,
  },
];
