const Seeder = require('mongoose-data-seed').Seeder;
const Message = require('../models/Message');
const data = [
  /* 1 */
  {
    _id: '5d0bbff417a2c5fa1a61e6e8',
    color: '#f26247',
    messageType: 'JOINED_ROOM',
    isTrashed: false,
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    text: 'Wesley joined reference room',
    autogenerated: true,
    timestamp: 1561051124701.0,
    __v: 0,
  },

  /* 2 */
  {
    _id: '5d0bbffc77adf7bc09a145d0',
    color: '#f26247',
    messageType: 'TOOK_CONTROL',
    isTrashed: false,
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    text: 'Wesley took control',
    autogenerated: true,
    timestamp: 1561051132233.0,
    __v: 0,
  },

  /* 3 */
  {
    _id: '5d0bc0084617c4dd3642c15c',
    color: '#f26247',
    messageType: 'TEXT',
    isTrashed: false,
    text: 'point d',
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    timestamp: 1561051144923.0,
    reference: {
      element: 'D',
      elementType: 'point',
      tab: 0,
    },
    __v: 0,
  },

  /* 4 */
  {
    _id: '5d0bc012be36fa3a63d04f00',
    color: '#f26247',
    messageType: 'TEXT',
    isTrashed: false,
    text: 'triangle t1',
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    timestamp: 1561051154499.0,
    reference: {
      element: 't1',
      elementType: 'poly',
      tab: 0,
    },
    __v: 0,
  },

  /* 5 */
  {
    _id: '5d0bc01ed2621d849ba059f5',
    color: '#f26247',
    messageType: 'TEXT',
    isTrashed: false,
    text: 'circle e',
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    timestamp: 1561051166131.0,
    reference: {
      element: 'E',
      elementType: 'point',
      tab: 0,
    },
    __v: 0,
  },

  /* 6 */
  {
    _id: '5d0bc02d933ab8d5066d7565',
    color: '#f26247',
    messageType: 'TEXT',
    isTrashed: false,
    text: 'segment b',
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    timestamp: 1561051181091.0,
    reference: {
      element: 'b',
      elementType: 'segment',
      tab: 0,
    },
    __v: 0,
  },

  /* 7 */
  {
    _id: '5d0bc039bd89f09d284bee20',
    color: '#f26247',
    messageType: 'RELEASED_CONTROL',
    isTrashed: false,
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    text: 'Wesley released control',
    autogenerated: true,
    timestamp: 1561051193957.0,
    __v: 0,
  },

  /* 8 */
  {
    _id: '5d0bc03b732ad02ae8d5062a',
    color: '#333',
    messageType: 'LEFT_ROOM',
    isTrashed: false,
    room: '5d0bbff1732ad02ae8d50614',
    user: '5ba289ba7223b9429888b8ed',
    text: 'Wesley left the room',
    autogenerated: true,
    timestamp: 1561051195717.0,
    __v: 0,
  },

  /* 9 */
  {
    _id: '5d0bc17ad4b447812eeb1390',
    color: '#f26247',
    messageType: 'JOINED_ROOM',
    isTrashed: false,
    user: '5ba289ba7223b9429888b8ed',
    room: '5d0bbff1732ad02ae8d50614',
    text: 'Wesley joined reference room',
    autogenerated: true,
    timestamp: 1561051514456.0,
    __v: 0,
  },
];

const MessagesSeeder = Seeder.extend({
  shouldRun: function() {
    return Message.count()
      .exec()
      .then(count => count === 0);
  },
  run: function() {
    return Message.create(data);
  },
});

module.exports = MessagesSeeder;
