// Should we store chat data in this component's state or in the
// redux store?
import React, { PureComponent } from 'react';
import ChatLayout from '../../Components/Chat/Chat';
class Chat extends PureComponent {
  state = {
    messages: [],
  }

  componentDidMount(){
    if (this.props.log[0].text) {
      this.setState({messages: [this.props.log[0]]})

    }
  }

  componentDidUpdate(prevProps) {
    const { log, index, reset, skipping, setCurrentMembers } = this.props;
    if (!prevProps.skipping && skipping) {
      let currentMembers = [];
      const messages = log.filter((entry, i) => {
        if (entry.autogenerated && i <= index) {
          if (entry.text.includes('joined')) {
            currentMembers.push(entry.user)
          }
          else {
            currentMembers = currentMembers.filter(user => {
              return entry.user._id !== user._id}
            )
          }
        }
        return i <= index && entry.text;
      })
      this.setState({messages,})
      reset();
      setCurrentMembers(currentMembers)
    }
    else if (log[index].text && (prevProps.log[prevProps.index]._id !== log[index]._id)) {
      this.setState(prevState => ({messages: [...prevState.messages, log[index]]}))
    }
  }

  render() {
    return (
      <ChatLayout messages={this.state.messages} replayer/>
    )
  }
}

export default Chat;
