// USER
// // UPDATE RESOURCES
export const GOT_USER = 'GOT_USER';
export const UPDATE_USER_ROOMS = 'UPDATE_USER_ROOMS';
export const UPDATE_USER_COURSES = 'UPDATE_USER_COURSES';
export const UPDATE_USER_ASSIGNMENTS = 'UPDATE_USER_ASSIGNMENTS';
export const UPDATE_USER_COURSE_ACCESS_NTFS = 'UPDATE_USER_COURSE_ACCESS_NTFS';
export const UPDATE_USER_COURSE_TEMPLATES = 'UPDATE_USER_COURSE_TEMPLATES';
export const UPDATE_USER_ROOM_TEMPLATES = 'UPDATE_USER_ROOM_TEMPLATES';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

// LOADING
export const START = 'START';
export const SUCCESS = 'SUCESS';
export const FAIL = 'FAIL';
export const ACCESS_SUCCESS = 'ACCESS_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR = 'CLEAR';

// COURSES
export const GOT_COURSES = 'GOT_COURSES';
export const CREATED_COURSE = 'CREATED_COURSE';
export const GOT_CURRENT_COURSE = 'GOT_CURRENT_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE_ROOMS = 'UPDATE_COURSE_ROOMS';
export const GRANT_ACCESS = 'GRANT_ACCESS';
export const CLEAR_COURSE = 'CLEAR_COURSE';

// ASSIGNMENTS
export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const GOT_ASSIGNMENTS = 'GOT_ASSIGNMENTS';
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';
export const UPDATE_ASSIGNMENT_ROOMS = 'UPDATE_ASSIGNMENT_ROOMS';
export const CREATED_ASSIGNMENT = 'CREATED_ASSIGNMENT';
export const CREATE_ASSIGNMENT_CONFIRMED = 'CREATE_ASSIGNMENT_CONFIRMED';
export const CLEAR_ASSIGNMENT = 'CLEAR_ASSIGNMENTS';

// ROOMS
export const GET_ROOMS = 'GET_ROOMS';
export const GOT_ROOMS = 'GOT_ROOMS';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const CREATED_ROOM = 'CREATED_ROOM';
export const CREATE_ROOM_CONFIRMED = 'CREATE_ROOM_CONFIRMED';
export const CLEAR_ROOM = 'CLEAR_ROOM';

// COURSE TEMPLATES
export const GOT_COURSE_TEMPLATES = 'GOT_COURSE_TEMPLATES';
export const GET_COURSE_TEMPLATES ='GET_COURSE_TEMPLATES';
export const UPDATE_COURSE_ASSIGNMENTS = 'UPDATE_COURSE_ASSIGNMENTS'
export const CREATE_COURSE_TEMPLATE = 'CREATE_COURSE_TEMPLATE';
export const CREATED_COURSE_TEMPLATE = 'CREATED_COURSE_TEMPLATE';

// ROOM TEMPLATES
export const GOT_ROOM_TEMPLATES = 'GOT_ROOM_TEMPLATES';
export const CREATED_ROOM_TEMPLATE = 'CREATED_ROOM_TEMPLATE';
