// USER
export const GOT_USER = 'GOT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_USER_ROOMS = 'UPDATE_USER_ROOMS';
export const ADD_USER_COURSES = 'ADD_USER_COURSES';
export const ADD_USER_ACTIVITIES = 'ADD_USER_ACTIVITIES';
export const UPDATE_USER_COURSE_ACCESS_NTFS = 'UPDATE_USER_COURSE_ACCESS_NTFS';
export const ADD_USER_COURSE_TEMPLATES = 'ADD_USER_COURSE_TEMPLATES';
export const REMOVE_USER_COURSE = 'REMOVE_USER_COURSE';
export const REMOVE_USER_ACTIVITIES = 'REMOVE_USER_ACTIVITIES';
export const REMOVE_USER_ROOMS = 'REMOVE_USER_ROOMS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const LOGOUT = 'LOGOUT';

// LOADING
export const START = 'START';
export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';
export const ACCESS_SUCCESS = 'ACCESS_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR = 'CLEAR';

// COURSES
export const GOT_COURSES = 'GOT_COURSES';
export const CREATED_COURSE = 'CREATED_COURSE';
export const GOT_CURRENT_COURSE = 'GOT_CURRENT_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_ROOMS = 'ADD_COURSE_ROOMS';
export const ADD_COURSE_ACTIVITIES = 'ADD_COURSE_ACTIVITIES';
export const GRANT_ACCESS = 'GRANT_ACCESS';
export const CLEAR_COURSE = 'CLEAR_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const REMOVE_COURSE_ACTIVITIES = 'REMOVE_COURSE_ACTIVITIES';
export const REMOVE_COURSE_ROOMS = 'REMOVE_COURSE_ROOMS';
export const ADD_COURSE_MEMBER = 'ADD_COURSE_MEMBER';

// ACTIVITIES
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GOT_ACTIVITIES = 'GOT_ACTIVITIES';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const ADD_ACTIVITY_ROOMS = 'ADD_ACTIVITY_ROOMS';
export const CREATED_ACTIVITY = 'CREATED_ACTIVITY';
export const CREATE_ACTIVITY_CONFIRMED = 'CREATE_ACTIVITY_CONFIRMED';
export const CLEAR_ACTIVITY = 'CLEAR_ACTIVITIES';
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';

// ROOMS
export const GET_ROOMS = 'GET_ROOMS';
export const GOT_ROOMS = 'GOT_ROOMS';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const CREATED_ROOM = 'CREATED_ROOM';
export const CREATE_ROOM_CONFIRMED = 'CREATE_ROOM_CONFIRMED';
export const CLEAR_ROOM = 'CLEAR_ROOM';
export const REMOVE_ROOM = 'REMOVE_ROOM';
export const ADD_ROOM_MEMBER = 'ADD_ROOM_MEMBER';
export const REMOVE_ROOM_MEMBER = 'REMOVE_ROOM_MEMBER';

// COURSE TEMPLATES
export const GOT_COURSE_TEMPLATES = 'GOT_COURSE_TEMPLATES';
export const GET_COURSE_TEMPLATES ='GET_COURSE_TEMPLATES';
export const UPDATE_COURSE_ACTIVITIES = 'UPDATE_COURSE_ACTIVITIES'
export const CREATE_COURSE_TEMPLATE = 'CREATE_COURSE_TEMPLATE';
export const CREATED_COURSE_TEMPLATE = 'CREATED_COURSE_TEMPLATE';

// TRASH
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const MOVE_CARD = 'MOVE_CARD';
