// USER
export const UPDATE_USER_ROOMS = 'UPDATE_USER_ROOMS';
export const UPDATE_USER_COURSES = 'UPDATE_USER_COURSES';
export const CLEAR_ERROR = 'CLEAR_ERROR'
// // LOGIN
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// // SIGNUP
export const SIGNUP = 'SIGNUP';


// ROOMS
export const GET_ROOMS = 'GET_ROOMS';
export const GOT_ROOMS = 'GOT_ROOMS';
export const CREATED_ROOM = 'CREATED_ROOM';
export const CREATE_ROOM_CONFIRMED = 'CREATE_ROOM_CONFIRMED';

// COURSES
export const GOT_COURSES = 'GOT_COURSES';
export const CREATED_COURSE = 'CREATED_COURSE';
