const mongoose = require('mongoose');
const ObjectId = mongoose.Schema.Types.ObjectId;
const Room = require('./Room.js');
const Message = new mongoose.Schema({
  user: {type: ObjectId, ref: 'User'},
  text: {type: String},
  room: {type: ObjectId, ref: 'Room', required: true},
  autogenerated: {type: Boolean},
  timestamp: {type: Number}, // SAVING THIS IN UNIX TIME FOR EASY SORTING but in MS
  reference: {
    element: {type: String},
    elementType: {type: String}
  },
  messageType: {type: String, enum: ['TEXT', 'TOOK_CONTROL', 'RELEASED_CONTROL'], default: 'TEXT'}
});

// Add this message to the room's chat
// @TODO for some reason I can't get $push to work
Message.pre('save', async function() {
  let controlledBy = '';
  if (this.messageType === 'TOOK_CONTROL') {
    controlledBy = this.user._id;
  }
  try {
    await Room.findByIdAndUpdate(this.room, {controlledBy, $addToSet: {chat: this._id}})
  }
  catch(err) {

  }
})
module.exports = mongoose.model('Message', Message);
